---
name: monitoring-stack

volumes:

  grafana-data:
    driver: local

  prometheus-data:
    driver: local

services:

  grafana:
    image: grafana/grafana:11.5.2
    container_name: grafana
    restart: unless-stopped
    # if running as root, set to 0; else find the right id with `id -u`
    user: '1000'
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=5d'

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    expose:
      - 9100
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'

  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    container_name: cadvisor
    restart: unless-stopped
    privileged: true
    expose:
      - 8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg

  oracle-db-om:
    image: container-registry.oracle.com/database/observability-exporter:1.5.5
    container_name: oracle-db-om
    restart: unless-stopped
    ports:
      - "9161:9161"
    environment:
      - DB_USERNAME=yourUser
      # - DB_ROLE=SYSDBA
      - DB_PASSWORD=yourPassword
      - DB_CONNECT_STRING=yourDb:1521/dbService
      - CUSTOM_METRICS=/exporter/custom-metrics.toml
    volumes:
      - ./oracle-exporter:/exporter
    stdin_open: true
    tty: true
