{
 "title": "Oracle Dashboard",
 "tags": [ "oracle" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Oracle Database Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Database Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "oracledb_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "SGA Max Size",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "oracledb_db_system_value{name=\"sga_max_size\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PGA Aggregate Limit",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "oracledb_db_system_value{name=\"pga_aggregate_limit\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Sessions",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "oracledb_sessions_value{status=\"ACTIVE\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "User commits",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "oracledb_activity_user_commits", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Execute count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "oracledb_activity_execute_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "oracledb_db_system_value{name=\"cpu_count\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database Type",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "oracledb_dbtype", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Database Platform",
   "type": "table",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 4 },
   "targets": [
    {
     "expr": "max(oracledb_db_platform_value) by (platform_name)",
     "legendFormat": "{{platform_name}}"
    }
   ]
  },
  { "title": "System Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Database CPU utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "oracledb_system_performance_value{metric_name=\"Host CPU Utilization (%)\"} * ignoring(metric_name) oracledb_system_performance_value{metric_name=\"Database CPU Time Ratio\"} / 100",
     "legendFormat": "%db"
    }
   ]
  },
  {
   "title": "Process count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 15, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "oracledb_process_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "AAS",
   "type": "stat",
   "description": "Average Active Sessions",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "oracledb_system_performance_value{metric_name=\"Average Active Sessions\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ASW",
   "type": "stat",
   "description": "(Average) Active Sessions Waiting",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(oracledb_sessions_active_sessions_waiting[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "System Wait Classes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Database Wait Times",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(oracledb_wait_time_administrative[$__rate_interval])",
     "legendFormat": "Administrative"
    },
    {
     "expr": "rate(oracledb_wait_time_application[$__rate_interval])",
     "legendFormat": "Application"
    },
    {
     "expr": "rate(oracledb_wait_time_cluster[$__rate_interval])",
     "legendFormat": "Cluster"
    },
    {
     "expr": "rate(oracledb_wait_time_commit[$__rate_interval])",
     "legendFormat": "Commit"
    },
    {
     "expr": "rate(oracledb_wait_time_concurrency[$__rate_interval])",
     "legendFormat": "Concurrency"
    },
    {
     "expr": "rate(oracledb_wait_time_configuration[$__rate_interval])",
     "legendFormat": "Configuration"
    },
    {
     "expr": "rate(oracledb_wait_time_network[$__rate_interval])",
     "legendFormat": "Network"
    },
    {
     "expr": "rate(oracledb_wait_time_other[$__rate_interval])",
     "legendFormat": "Other"
    },
    {
     "expr": "rate(oracledb_wait_time_scheduler[$__rate_interval])",
     "legendFormat": "Scheduler"
    },
    {
     "expr": "rate(oracledb_wait_time_user_io[$__rate_interval])",
     "legendFormat": "User I/O"
    },
    {
     "expr": "rate(oracledb_wait_time_system_io[$__rate_interval])",
     "legendFormat": "System I/O"
    }
   ]
  },
  { "title": "Cache Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Cache Hit Ratios",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "oracledb_cache_hit_ratio_value", "legendFormat": "{{cache_hit_type}}" }
   ]
  },
  { "title": "Top SQL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Top SQL by elapsed time running",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "max(oracledb_top_sql_elapsed) by (sql_id, sql_text)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Tablespaces", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Tablespace status",
   "type": "table",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "oracledb_tablespace_used_percent",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tablespace usage over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "oracledb_tablespace_used_percent",
     "legendFormat": "{{tablespace}}"
    }
   ]
  },
  { "title": "Extras", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Archivelog usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(oracledb_fra_space_used - oracledb_fra_space_reclaimable) / oracledb_fra_space_limit * 100",
     "legendFormat": "Archivelog"
    }
   ]
  },
  {
   "title": "Deadlocks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "targets": [
    { "expr": "oracledb_deadlocks_total", "legendFormat": "deadlocks" }
   ]
  }
 ]
}